import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { Resend } from "resend";
import { auth } from "@/server/auth";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: NextRequest) {
    try {
        const session = await auth();
        if (!session?.user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const body = await req.json() as unknown;

        // Privacy: only destructure the three fields we actually need.
        // Any additional fields (e.g. formData, attributes) sent by an older
        // client are silently dropped here and never logged or forwarded.
        const { to, formTitle, formHTML } = body as {
            to?: unknown;
            formTitle?: unknown;
            formHTML?: unknown;
        };

        const toStr = String(to);
        const titleStr = String(formTitle);
        const htmlStr = typeof formHTML === "string" ? formHTML : "";

        if (!toStr || !titleStr) {
            return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
        }

        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(toStr)) {
            return NextResponse.json({ error: "Invalid email address" }, { status: 400 });
        }

        const { data, error } = await resend.emails.send({
            from: process.env.RESEND_FROM_EMAIL ?? "Formify <onboarding@resend.dev>",
            to: [toStr],
            subject: `Formify: ${titleStr}`,
            html: `
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <style>
                        body {
                            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                            line-height: 1.6;
                            color: #111827;
                            max-width: 600px;
                            margin: 0 auto;
                            padding: 20px;
                            background-color: #f9fafb;
                        }
                        .container {
                            background-color: #ffffff;
                            border-radius: 8px;
                            padding: 30px;
                            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
                        }
                        .header {
                            border-bottom: 3px solid #2149A1;
                            padding-bottom: 20px;
                            margin-bottom: 30px;
                        }
                        h1 { color: #2149A1; font-size: 24px; margin: 0 0 10px 0; }
                        .subtitle { color: #6b7280; font-size: 14px; margin: 0; }
                        .content { margin-top: 20px; }
                        .footer {
                            margin-top: 40px;
                            padding-top: 20px;
                            border-top: 1px solid #e5e7eb;
                            text-align: center;
                            font-size: 12px;
                            color: #9ca3af;
                        }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <div class="header">
                            <h1>${titleStr}</h1>
                            <p class="subtitle">Generated by Formify on ${new Date().toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
                hour: "2-digit",
                minute: "2-digit",
            })}</p>
                        </div>
                        <div class="content">
                            ${htmlStr}
                        </div>
                        <div class="footer">
                            <p>This form was sent from Formify</p>
                        </div>
                    </div>
                </body>
                </html>
            `,
        });

        if (error) {
            // Log only the Resend error object — never log htmlStr, titleStr, or toStr
            // to avoid PII appearing in server logs.
            console.error("[email] Resend error:", error.name, error.message);

            let errorMessage = "Failed to send email";
            if (error.message?.includes("domain is not verified")) {
                errorMessage =
                    "Testing mode: Only emails to @resend.dev addresses work without domain verification. " +
                    "Use \'delivered@resend.dev\' for testing, or verify your domain at https://resend.com/domains";
            } else if (error.message?.includes("API key")) {
                errorMessage =
                    "Email service not configured. Please add RESEND_API_KEY to environment variables.";
            }

            return NextResponse.json({ error: errorMessage }, { status: 500 });
        }

        // Log only the message ID — not the recipient or subject — to avoid PII in logs.
        console.log("[email] Sent, messageId:", data?.id);

        return NextResponse.json({ success: true, messageId: data?.id });

    } catch (error) {
        // Log only the error class/message, never the request body.
        const label = error instanceof Error ? error.message : "unknown";
        console.error("[email] Internal error:", label);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}